#!/usr/bin/env python3
"""
Generate All Figures for UHDM AGN Paper
========================================

Master script to generate all publication-quality figures.

Usage:
    python generate_figures.py --output figures/
    python generate_figures.py --output figures/ --figures 1,2,3

Author: Kirti Patidar
Version: 2.0-FINAL
Date: October 24, 2025
"""

import argparse
import sys
import os
import subprocess
from pathlib import Path


def run_script(script_name, description):
    """
    Run a Python script and handle errors.

    Parameters:
    -----------
    script_name : str
        Name of the script to run
    description : str
        Description of what the script does
    """
    print(f"\n{'='*60}")
    print(f"Generating: {description}")
    print(f"Script: {script_name}")
    print(f"{'='*60}\n")

    try:
        result = subprocess.run(
            [sys.executable, script_name],
            check=True,
            capture_output=True,
            text=True
        )
        print(result.stdout)
        if result.stderr:
            print("Warnings:", result.stderr)
        print(f"✓ {description} - COMPLETE")
        return True
    except subprocess.CalledProcessError as e:
        print(f"✗ ERROR in {script_name}:")
        print(e.stdout)
        print(e.stderr)
        return False
    except Exception as e:
        print(f"✗ UNEXPECTED ERROR: {e}")
        return False


def main():
    """Main execution function."""
    parser = argparse.ArgumentParser(
        description='Generate all figures for UHDM AGN paper',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Generate all figures
  python generate_figures.py --output figures/

  # Generate specific figures only
  python generate_figures.py --output figures/ --figures 1,2,4

  # Generate with verbose output
  python generate_figures.py --output figures/ --verbose
        """
    )

    parser.add_argument(
        '--output',
        type=str,
        default='../figures/',
        help='Output directory for figures (default: ../figures/)'
    )

    parser.add_argument(
        '--figures',
        type=str,
        default='all',
        help='Comma-separated list of figure numbers to generate (default: all)'
    )

    parser.add_argument(
        '--verbose',
        action='store_true',
        help='Verbose output'
    )

    args = parser.parse_args()

    # Ensure output directory exists
    output_dir = Path(args.output)
    output_dir.mkdir(parents=True, exist_ok=True)

    # Define figure generation tasks
    figures = {
        '1': ('eft_cross_sections.py', 'Figure 1: EFT Validity (Corrected)'),
        '2': ('grmhd_acceleration.py', 'Figure 2: Maximum Lorentz Factors'),
        '3': ('eft_cross_sections.py', 'Figure 3: Production Rates vs Mass'),
        '4': ('observational_constraints.py', 'Figure 4: Multi-Messenger Constraints'),
        'S1': ('monte_carlo_sampling.py', 'Figure S1: MCMC Diagnostics')
    }

    # Parse which figures to generate
    if args.figures.lower() == 'all':
        figures_to_generate = list(figures.keys())
    else:
        figures_to_generate = [f.strip() for f in args.figures.split(',')]

    # Validate figure numbers
    invalid_figs = [f for f in figures_to_generate if f not in figures]
    if invalid_figs:
        print(f"Warning: Invalid figure numbers: {invalid_figs}")
        print(f"Valid options: {', '.join(figures.keys())}")
        sys.exit(1)

    print(f"\n{'='*60}")
    print(f"UHDM AGN Figure Generation")
    print(f"{'='*60}")
    print(f"Output directory: {output_dir.absolute()}")
    print(f"Figures to generate: {', '.join(figures_to_generate)}")
    print(f"{'='*60}\n")

    # Change to code directory
    code_dir = Path(__file__).parent
    os.chdir(code_dir)

    # Generate figures
    success_count = 0
    failed_count = 0

    # Track which scripts we've already run (to avoid duplicates)
    run_scripts = set()

    for fig_num in figures_to_generate:
        script_name, description = figures[fig_num]

        # Skip if we've already run this script
        if script_name in run_scripts:
            print(f"\n✓ {description} - Already generated by {script_name}")
            success_count += 1
            continue

        if run_script(script_name, description):
            success_count += 1
            run_scripts.add(script_name)
        else:
            failed_count += 1

    # Summary
    print(f"\n{'='*60}")
    print(f"GENERATION COMPLETE")
    print(f"{'='*60}")
    print(f"Success: {success_count}/{len(figures_to_generate)}")
    print(f"Failed:  {failed_count}/{len(figures_to_generate)}")

    if failed_count == 0:
        print("\n✓ All figures generated successfully!")
        print(f"  Output location: {output_dir.absolute()}")
        return 0
    else:
        print(f"\n✗ {failed_count} figure(s) failed to generate")
        print("  Check error messages above for details")
        return 1


if __name__ == '__main__':
    sys.exit(main())
